# Copyright Advanced Micro Devices, Inc. All rights reserved.

"""Persistent-agent system prompts.

Two flavours of content live in this package:

* ``orchestration.md``, ``critic.md``, ``kernel.md``, ``robustness.md`` —
  hand-edited markdown fragments. ``orchestration.md`` is intentionally
  reduced to the rules / contracts that don't depend on which actions
  are enabled; everything else is generated by :mod:`prompt_builder`.

* :mod:`prompt_builder` — composes the full Orchestration system prompt
  from :class:`ActionMetadata`, the rules fragment, and run-level
  parameters (kernel_enabled, framework, objective, max_minutes). This
  replaces the legacy ``orchestration.no_kernel.md`` file: there is now
  only one source of truth and the kernel-vs-no-kernel split is a
  parameter.
"""
