# Auto-generated by framework-agent/scripts/install.sh
# Do not hand-edit; rerun install.sh to regenerate.
_FA_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
export FRAMEWORK_AGENT_ROOT="$(cd "${_FA_SCRIPT_DIR}/.." && pwd)"
export FRAMEWORK_AGENT_KB_DIR="${FRAMEWORK_AGENT_ROOT}/kb"
export PATH="/workdir/hyperloom/venv/bin:${PATH:-}"
unset _FA_SCRIPT_DIR
