# Auto-generated by framework-agent/scripts/install.sh
export FRAMEWORK_AGENT_ROOT="/wekafs/zgong/Hyperloom/framework-agent"
export FRAMEWORK_AGENT_KB_DIR="/wekafs/zgong/Hyperloom/framework-agent/kb"
export PATH="/opt/venv/bin:${PATH:-}"
