#!/usr/bin/env bash
# framework-agent installer (P2 PR-D).
#
# Idempotent. Used both standalone (developer pod setup) and chained
# from inference_optimizer/scripts/install.sh on Hyperloom sandboxes.
# Targets a single Python venv (PEP 660 editable install) so the `fa`
# console script is on PATH alongside `inference_optimizer`.
#
# Env vars:
#   FRAMEWORK_AGENT_ROOT   default: this script's parent (computed below)
#   VENV_PYTHON            preferred Python interpreter. Auto-detects
#                          /opt/venv/bin/python on hyperloom/sgl-workspace
#                          containers (canonical ROCm stack). Set
#                          FRAMEWORK_AGENT_FORCE_PYTHON=1 to opt out of the
#                          auto-detect when VENV_PYTHON is explicitly set
#                          elsewhere.
#   PIP                    explicit override (ignored when VENV_PYTHON is set).
#                          Default: `pip` on PATH.
#   FRAMEWORK_AGENT_EXTRAS comma-separated extras to install; default 'ast,test'
#                          (libcst + patch-ng + pytest + jsonschema)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
FRAMEWORK_AGENT_ROOT="${FRAMEWORK_AGENT_ROOT:-${PROJECT_ROOT}}"
KB_DIR="${FRAMEWORK_AGENT_KB_DIR:-${FRAMEWORK_AGENT_ROOT}/kb}"
EXTRAS="${FRAMEWORK_AGENT_EXTRAS:-ast,test}"

# Prefer /opt/venv/bin/python on hyperloom/sgl-workspace containers. The
# system /usr/bin/pip is too old (22.0.2 on Ubuntu 22.04) to honour the
# PEP 660 build_editable hook our pyproject declares, so editable install
# fails with "build backend is missing the 'build_editable' hook". Mirror
# inference_optimizer/scripts/install.sh::resolve_python.
if [ -x "/opt/venv/bin/python" ] && [ "${FRAMEWORK_AGENT_FORCE_PYTHON:-0}" != "1" ]; then
    if [ -n "${VENV_PYTHON:-}" ] && [ "${VENV_PYTHON}" != "/opt/venv/bin/python" ]; then
        echo "[framework-agent/install.sh] preferring /opt/venv/bin/python over VENV_PYTHON=${VENV_PYTHON} (canonical ROCm stack)"
        echo "[framework-agent/install.sh]   set FRAMEWORK_AGENT_FORCE_PYTHON=1 to honour VENV_PYTHON verbatim"
    fi
    VENV_PYTHON="/opt/venv/bin/python"
fi

if [ -n "${VENV_PYTHON:-}" ] && [ -x "${VENV_PYTHON}" ]; then
    PIP="${VENV_PYTHON} -m pip"
elif [ -n "${PIP:-}" ]; then
    : # honour explicit override
else
    PIP="$(command -v pip || true)"
    if [ -z "${PIP}" ]; then
        echo "ERROR: install.sh: pip not found on PATH; set VENV_PYTHON or PIP." >&2
        exit 1
    fi
fi

echo "[framework-agent/install.sh] root=${FRAMEWORK_AGENT_ROOT}"
echo "[framework-agent/install.sh] extras=${EXTRAS}"
echo "[framework-agent/install.sh] pip=${PIP}"

# PEP 660 editable install. Idempotent -- re-running upgrades the wheel
# metadata in place but does not duplicate distributions.
${PIP} install -e "${PROJECT_ROOT}[${EXTRAS}]"

mkdir -p "${KB_DIR}"

# env.sh is consumed by inference_optimizer's _preflight() probe + by
# operators sourcing the env into an interactive shell.
cat > "${SCRIPT_DIR}/env.sh" <<EOF
# Auto-generated by framework-agent/scripts/install.sh
export FRAMEWORK_AGENT_ROOT="${FRAMEWORK_AGENT_ROOT}"
export FRAMEWORK_AGENT_KB_DIR="${KB_DIR}"
export PATH="$(dirname "${PIP%% *}"):\${PATH:-}"
EOF

echo "[framework-agent/install.sh] OK -- 'fa --help' should resolve now."
