#!/usr/bin/env bash
# Framework Agent installer.
#
# Base install is intentionally small and deterministic:
#   - pip install -e . (this package)
#
# The installer does NOT install kernel-agent / critic-agent / TraceLens etc.
# framework-agent is fully standalone.

set -euo pipefail

# When invoked as `bash /path/to/framework-agent/scripts/install.sh`, the
# script lives at <FRAMEWORK_AGENT_ROOT>/scripts/install.sh, so its
# parent directory IS the framework-agent root. This makes the default
# work both inside a Claw sandbox (which mounts wekafs at an arbitrary
# path) and in any other checkout location; callers can still override
# via the FRAMEWORK_AGENT_ROOT env var.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMEWORK_AGENT_ROOT_DEFAULT="$(cd "${SCRIPT_DIR}/.." && pwd)"

WORKSPACE_PATH="${WORKSPACE_PATH:-/workspace}"
FRAMEWORK_AGENT_ROOT="${FRAMEWORK_AGENT_ROOT:-${FRAMEWORK_AGENT_ROOT_DEFAULT}}"
FRAMEWORK_AGENT_KB_DIR="${FRAMEWORK_AGENT_KB_DIR:-${FRAMEWORK_AGENT_ROOT}/kb}"

# Prefer the in-container Python venv shipped by the plugin's image
# (e.g. the sglang ROCm image ships torch/sglang under /opt/venv). The
# system /usr/bin/python3 in those images is a bare 3.10 with no ML deps.
# Callers can still override via the PYTHON env var.
if [[ -z "${PYTHON:-}" && -x /opt/venv/bin/python ]]; then
    PYTHON=/opt/venv/bin/python
fi
PYTHON="${PYTHON:-$(command -v python3)}"
if [[ -z "$PYTHON" ]]; then
    echo "ERROR: python3 not found" >&2
    exit 1
fi

# Editable install via PEP 660 requires pip >= 23. The Ubuntu 22.04 system
# pip in many Claw sandbox base images is 22.0.2 which fails with:
#   "build backend is missing the 'build_editable' hook"
# Upgrading is cheap and idempotent. We tolerate failures (|| true) so a
# locked-down environment without internet can still proceed if pip is
# already >= 23 (pip just no-ops the upgrade).
"$PYTHON" -m pip install --upgrade --quiet "pip>=23" || true

cd "$FRAMEWORK_AGENT_ROOT"

# 1. Editable install with test extra
"$PYTHON" -m pip install -e ".[test]"

# 2. Detect framework source trees (WARN-only)
for tree in /sgl-workspace/vllm /sgl-workspace/sglang; do
    if [[ ! -d "$tree" ]]; then
        echo "WARN: $tree not present; explore commands targeting that framework will fail at git fetch time" >&2
    fi
done

# 3. Generate runtime env.sh under framework-agent root (NOT under src/).
# Putting `dirname $PYTHON` first on PATH ensures subsequent `python3`/`fa`
# lookups hit the venv we installed into (especially important when the
# host image's /usr/bin/python3 lacks torch / sglang).
ENV_SH="$FRAMEWORK_AGENT_ROOT/runtime/env.sh"
mkdir -p "$(dirname "$ENV_SH")"
cat > "$ENV_SH" <<EOF
# Auto-generated by framework-agent/scripts/install.sh
export FRAMEWORK_AGENT_ROOT="$FRAMEWORK_AGENT_ROOT"
export FRAMEWORK_AGENT_KB_DIR="$FRAMEWORK_AGENT_KB_DIR"
export PATH="$(dirname "$PYTHON"):\${PATH:-}"
EOF

# 4. Smoke test
"$PYTHON" -m framework_agent.runtime.cli schema > /dev/null

echo "OK: framework-agent installed at $FRAMEWORK_AGENT_ROOT"
echo "Source $ENV_SH to set env vars in your shell."
