# Copyright Advanced Micro Devices, Inc. All rights reserved.

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/ci"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
