#!/usr/bin/env bash
# Bootstrap the BYOI toolchain inside the RayJob head pod.
#
# Submitted by ``inference_optimizer.multi_node bootstrap`` via the Ray
# Dashboard REST ``/api/jobs/`` endpoint, which means this script runs
# INSIDE the RayJob head pod, not in the Claw sandbox.
#
# Idempotent: a marker file at ``$BOOTSTRAP_MARKER`` short-circuits the
# whole script on subsequent calls. To force a re-run pass ``--force`` or
# ``unset`` the marker first.
#
# Renders ``/etc/profile.d/hyperloom-env.sh`` from the env it can see,
# so every later REST job that does ``source /etc/profile.d/hyperloom-env.sh``
# picks up the same PATH / *_API_KEY / *_BASE_URL the bootstrap saw.

set -euo pipefail

BOOTSTRAP_MARKER="${BOOTSTRAP_MARKER:-/opt/hyperloom/.bootstrap_done}"
HYPERLOOM_VENV="${HYPERLOOM_VENV:-/opt/venv}"
LOG_DIR="${LOG_DIR:-/var/log/hyperloom}"
ENV_FILE="${ENV_FILE:-/etc/profile.d/hyperloom-env.sh}"

FORCE=0
for arg in "$@"; do
    case "$arg" in
        --force) FORCE=1 ;;
        *) echo "bootstrap.sh: unknown arg: $arg" >&2; exit 2 ;;
    esac
done

mkdir -p "$LOG_DIR" "$(dirname "$BOOTSTRAP_MARKER")"

if [ "$FORCE" -eq 0 ] && [ -f "$BOOTSTRAP_MARKER" ]; then
    echo "bootstrap.sh: marker $BOOTSTRAP_MARKER present; skipping. Pass --force to re-run."
    exit 0
fi

# --- 1. Verify the framework venv. The RayJob image (sglang/vllm) ships
#        /opt/venv with the framework already installed; we only fail loud
#        if it's missing.
if [ ! -x "$HYPERLOOM_VENV/bin/python3" ]; then
    echo "bootstrap.sh: ERROR — $HYPERLOOM_VENV/bin/python3 not found." >&2
    echo "             expected the framework image to ship a venv at /opt/venv." >&2
    exit 1
fi

# --- 2. (removed) OOB CLI install. The multi-node kernel-agent path uses
#        ``multi_node kernel-bench`` (NodeAffinity-hard-pinned to the head
#        pod via ``kernel_bench_multinode.py``); the head pod runs the
#        bench script directly, no OOB CLI is invoked inside the pod.
#        ``oob_submit.run_via_ray`` (the legacy single-node ray.remote
#        entrypoint) is not the path LLMs are prompted to take on
#        ``--nodes >= 2``. See ``multi_node/SKILL.md`` and
#        ``kernel-agent/tools/kernel_optimization.py:1244-1283``.

# --- 2c. (removed, multi-node only) claude/codex CLI install.
#        Multi-node head pod never invokes claude/codex CLI directly:
#        claude_agent_sdk runs as a Python lib inside the sandbox;
#        critic-agent runs as a sandbox subprocess; kernel-bench fans out
#        a python bench script (NodeAffinity-pinned to head) without
#        forking any CLI. So Node.js + npm packages are not needed here.

# --- 3. Render /etc/profile.d/hyperloom-env.sh so every later REST job
#        can ``source`` it and inherit the same PATH + credentials. We
#        only emit keys that are actually set in this process env so we
#        don't leak ``KEY=`` empty placeholders (which would shadow real
#        env later). Keys we care about: ADDENDUM-13's credential set
#        plus the venv PATH.
echo "bootstrap.sh: writing $ENV_FILE"
{
    echo "# Generated by inference_optimizer.multi_node bootstrap.sh — DO NOT EDIT."
    echo "export PATH=\"$HYPERLOOM_VENV/bin:\${PATH}\""
    for k in OOB_API_KEY AMD_LLM_API_KEY LLM_API_KEY \
             ANTHROPIC_API_KEY OPENAI_API_KEY SAFE_API_KEY \
             OOB_BASE_URL ANTHROPIC_BASE_URL OPENAI_BASE_URL \
             ANTHROPIC_CUSTOM_HEADERS; do
        v="${!k:-}"
        if [ -n "$v" ]; then
            # Single-quote the value verbatim so embedded `$`/`"` don't
            # get re-evaluated when the env file is sourced later.
            esc=$(printf "%s" "$v" | sed "s/'/'\\\\''/g")
            echo "export $k='$esc'"
        fi
    done
} > "$ENV_FILE"
chmod 0644 "$ENV_FILE"

# --- 4. Mark done.
date -u +"%Y-%m-%dT%H:%M:%SZ" > "$BOOTSTRAP_MARKER"
echo "bootstrap.sh: OK ($BOOTSTRAP_MARKER)"
