# SPDX-FileCopyrightText: 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Materialize Forge AgentHooks as Codex managed command hooks."""

from __future__ import annotations

import json
import shlex
import sys
from pathlib import Path

from kernelforge.agent_backends.base import AgentRunSpec
from kernelforge.durable_io import atomic_write_text

_GUARD_STATE_NAME = "forge_guard_state.json"
_CONFIG_NAME = "config.toml"
_MAX_STOP_DENIALS = 3


def guard_state_path(codex_home: Path) -> Path:
    return codex_home / _GUARD_STATE_NAME


def materialize_codex_managed_hooks(
    *,
    codex_home: Path,
    spec: AgentRunSpec,
) -> None:
    """Write Codex config.toml hooks that delegate to ``codex_hook_runner``."""
    if spec.hooks is None:
        return
    codex_home.mkdir(parents=True, exist_ok=True)
    staging_root = str(Path(spec.cwd).resolve())
    state = {
        "staging_root": staging_root,
        "max_stop_denials": _MAX_STOP_DENIALS,
        "stop_denials": 0,
        "deny_shell_tools": bool(spec.hooks.pre_tool_use),
    }
    atomic_write_text(
        guard_state_path(codex_home),
        json.dumps(state, indent=2, sort_keys=True) + "\n",
    )
    runner = shlex.quote(_hook_runner_argv())
    state_arg = shlex.quote(str(guard_state_path(codex_home)))
    pre_cmd = f"{runner} --state {state_arg} pre_tool_use"
    stop_cmd = f"{runner} --state {state_arg} stop"
    config_text = "\n".join(
        [
            "# Generated by KernelForge for one Forge agent session.",
            "[[hooks.PreToolUse]]",
            'matcher = ".*"',
            "[[hooks.PreToolUse.hooks]]",
            'type = "command"',
            f"command = {json.dumps(pre_cmd)}",
            "async = false",
            "timeout = 30",
            "",
            "[[hooks.Stop]]",
            "[[hooks.Stop.hooks]]",
            'type = "command"',
            f"command = {json.dumps(stop_cmd)}",
            "async = false",
            "timeout = 30",
            "",
        ]
    )
    atomic_write_text(codex_home / _CONFIG_NAME, config_text)


def _hook_runner_argv() -> str:
    return f"{sys.executable} -m kernelforge.agent_backends.codex_hook_runner"


__all__ = ["guard_state_path", "materialize_codex_managed_hooks"]
