# SPDX-FileCopyrightText: 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Breakdown recorder: author-time capture of ``session_breakdown.json`` data."""

from __future__ import annotations

from . import instrument
from .assembler import (
    BASELINE_EVENT_SECTIONS,
    EVENT_SECTIONS,
    KERNEL_EVENT_SECTIONS,
    ROOFLINE_EVENT_SECTIONS,
    assemble_parts,
    baseline_event_parts,
    event_parts,
    has_parts,
    kernel_event_parts,
    parts_dir,
    roofline_event_parts,
)
from .event_ids import EVENT_ID_SEPARATOR, EventId, event_id, fragment_key, parse_event_id
from .event_rows import (
    EVENT_ID_FIELD,
    SCOPE_FIELDS,
    group_rows,
    rows_for_event,
    sort_rows,
    wire_row,
    wire_rows,
)
from .event_finalize import finalize_events
from .event_sink import EventSink, RecordSink, make_sink
from .event_timeline import (
    EVENT_STATUS_INTERRUPTED,
    EVENT_STATUS_RUNNING,
    RESIDUAL_NO_EVENT,
    RESIDUAL_RUNNING,
    TERMINAL_EVENT_STATUSES,
    TIMELINE_SEQUENCE_FIELD,
    ResidualEvent,
    build_envelope,
    finish_event,
    open_event,
    residual_events,
)
from .trace import TRACE, TRACE_ENV, enable_trace, trace_enabled
from .instrument import (
    record_action_operation,
    record_adoption,
    record_artifact,
    record_critic_iteration,
    record_kernel_backend_result,
    record_kernel_discovery,
    record_kernel_dispatch,
    record_kernel_e2e,
    record_kernel_invocations,
    record_kernel_strategy_selection,
    record_native_kernel_run_start,
    record_native_kernel_run_result,
    record_geak_e2e_attempt,
    record_geak_operation,
    record_gemm_tuning_operation,
    record_measurement,
    record_operation,
    record_phase_event,
    record_phase_transition,
    record_robustness_signal,
    record_run_snapshot,
    record_singleton_section,
    record_specialist_round,
    record_subject,
    record_tool_version,
    record_trace_event,
    snapshot_state_sections,
)
from .recorder import (
    DERIVED_SECTIONS,
    SECTION_SHAPES,
    Recorder,
    SectionShape,
    get_recorder,
    recorder_for,
    section_shape,
)

__all__ = [
    "BASELINE_EVENT_SECTIONS",
    "DERIVED_SECTIONS",
    "EVENT_ID_FIELD",
    "EVENT_ID_SEPARATOR",
    "EVENT_STATUS_INTERRUPTED",
    "EVENT_STATUS_RUNNING",
    "EVENT_SECTIONS",
    "KERNEL_EVENT_SECTIONS",
    "ROOFLINE_EVENT_SECTIONS",
    "RESIDUAL_NO_EVENT",
    "RESIDUAL_RUNNING",
    "SCOPE_FIELDS",
    "SECTION_SHAPES",
    "TERMINAL_EVENT_STATUSES",
    "TIMELINE_SEQUENCE_FIELD",
    "EventId",
    "EventSink",
    "RecordSink",
    "Recorder",
    "ResidualEvent",
    "SectionShape",
    "TRACE",
    "TRACE_ENV",
    "assemble_parts",
    "baseline_event_parts",
    "build_envelope",
    "enable_trace",
    "event_id",
    "finalize_events",
    "finish_event",
    "fragment_key",
    "get_recorder",
    "group_rows",
    "has_parts",
    "instrument",
    "event_parts",
    "kernel_event_parts",
    "roofline_event_parts",
    "make_sink",
    "open_event",
    "parse_event_id",
    "parts_dir",
    "record_action_operation",
    "record_adoption",
    "record_artifact",
    "record_critic_iteration",
    "record_kernel_backend_result",
    "record_kernel_discovery",
    "record_kernel_dispatch",
    "record_kernel_e2e",
    "record_kernel_invocations",
    "record_kernel_strategy_selection",
    "record_native_kernel_run_start",
    "record_native_kernel_run_result",
    "record_geak_e2e_attempt",
    "record_geak_operation",
    "record_gemm_tuning_operation",
    "record_measurement",
    "record_operation",
    "record_phase_event",
    "record_phase_transition",
    "record_robustness_signal",
    "record_run_snapshot",
    "record_singleton_section",
    "record_specialist_round",
    "record_subject",
    "record_tool_version",
    "record_trace_event",
    "recorder_for",
    "residual_events",
    "rows_for_event",
    "snapshot_state_sections",
    "section_shape",
    "sort_rows",
    "trace_enabled",
    "wire_row",
    "wire_rows",
]
