#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

# Bootstrap the BYOI toolchain inside the RayJob head pod.
#
# Submitted by ``hyperloom.inference_optimizer.multi_node bootstrap`` via the Ray
# Dashboard REST ``/api/jobs/`` endpoint, which means this script runs
# INSIDE the RayJob head pod, not in the Claw sandbox.
#
# Idempotent: a marker file at ``$BOOTSTRAP_MARKER`` short-circuits the
# whole script on subsequent calls. To force a re-run pass ``--force`` or
# ``unset`` the marker first.
#
# Renders ``/etc/profile.d/hyperloom-env.sh`` from the env it can see,
# so every later REST job that does ``source /etc/profile.d/hyperloom-env.sh``
# picks up the same PATH / *_API_KEY / *_BASE_URL the bootstrap saw.

set -euo pipefail

BOOTSTRAP_MARKER="${BOOTSTRAP_MARKER:-/opt/hyperloom/.bootstrap_done}"
HYPERLOOM_VENV="${HYPERLOOM_VENV:-/opt/venv}"
LOG_DIR="${LOG_DIR:-/var/log/hyperloom}"
ENV_FILE="${ENV_FILE:-/etc/profile.d/hyperloom-env.sh}"

FORCE=0
for arg in "$@"; do
    case "$arg" in
        --force) FORCE=1 ;;
        *) echo "bootstrap.sh: unknown arg: $arg" >&2; exit 2 ;;
    esac
done

mkdir -p "$LOG_DIR" "$(dirname "$BOOTSTRAP_MARKER")"

if [ "$FORCE" -eq 0 ] && [ -f "$BOOTSTRAP_MARKER" ]; then
    echo "bootstrap.sh: marker $BOOTSTRAP_MARKER present; skipping. Pass --force to re-run."
    exit 0
fi

# --- 1. Verify the framework venv. The RayJob image (sglang/vllm) ships
#        /opt/venv with the framework already installed; we only fail loud
#        if it's missing.
if [ ! -x "$HYPERLOOM_VENV/bin/python3" ]; then
    echo "bootstrap.sh: ERROR — $HYPERLOOM_VENV/bin/python3 not found." >&2
    echo "             expected the framework image to ship a venv at /opt/venv." >&2
    exit 1
fi

# --- 2. Render /etc/profile.d/hyperloom-env.sh so every later REST job
#        can ``source`` it and inherit the same PATH + credentials. We
#        only emit keys that are actually set in this process env so we
#        don't leak ``KEY=`` empty placeholders (which would shadow real
#        env later). Keys we care about: ADDENDUM-13's credential set
#        plus the venv PATH.
echo "bootstrap.sh: writing $ENV_FILE"
{
    echo "# Generated by hyperloom.inference_optimizer.multi_node bootstrap.sh — DO NOT EDIT."
    echo "export PATH=\"$HYPERLOOM_VENV/bin:\${PATH}\""
    for k in AMD_LLM_API_KEY LLM_API_KEY LLM_GATEWAY_KEY GEAK_API_KEY \
             ANTHROPIC_API_KEY OPENAI_API_KEY SAFE_API_KEY \
             LLM_API_BASE GEAK_BASE_URL ANTHROPIC_BASE_URL OPENAI_BASE_URL \
             ANTHROPIC_CUSTOM_HEADERS OPENAI_CUSTOM_HEADERS; do
        v="${!k:-}"
        if [ -n "$v" ]; then
            # Single-quote the value verbatim so embedded `$`/`"` don't
            # get re-evaluated when the env file is sourced later.
            esc=$(printf "%s" "$v" | sed "s/'/'\\\\''/g")
            echo "export $k='$esc'"
        fi
    done
} > "$ENV_FILE"
chmod 0644 "$ENV_FILE"

# --- 3. Mark done.
date -u +"%Y-%m-%dT%H:%M:%SZ" > "$BOOTSTRAP_MARKER"
echo "bootstrap.sh: OK ($BOOTSTRAP_MARKER)"
