ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:26.01-py3
FROM ${BASE_IMAGE}

WORKDIR /workspace

RUN pip install --no-cache-dir \
    pyyaml \
    pybind11 \
    ninja \
    packaging \
    transformers \
    sentencepiece

# Copy patch files
WORKDIR /workspace/code/patches
COPY patches/primus_evaluator.patch .
COPY patches/megatron_validation_consumed_samples_v0.15.3.patch .

WORKDIR /workspace/deps
RUN git clone --recursive https://github.com/AMD-AIG-AIMA/Primus.git && \
    cd Primus && \
    git checkout main && \
    git submodule update --init --recursive && \
    pip install -r requirements.txt && \
    git apply /workspace/code/patches/primus_evaluator.patch 

RUN cd /workspace/deps/Primus/third_party/Megatron-LM && \
    git fetch origin tag v0.15.3 --no-tags && \
    git checkout v0.15.3 && \
    git submodule update --init --recursive && \
    git apply /workspace/code/patches/megatron_validation_consumed_samples_v0.15.3.patch && \
    pip install -e . --no-deps

RUN pip install --no-build-isolation --upgrade "git+https://github.com/NVIDIA/TransformerEngine.git@v2.12"

ENV PYTHONPATH="/workspace/deps/Primus:/workspace/deps/Primus/third_party/Megatron-LM"

WORKDIR /workspace/code
COPY . .

ARG MLPERF_PAT
RUN pip install git+https://x-access-token:${MLPERF_PAT}@github.com/AMD-MLPerf/primus-mllog.git@suachong/update-ttt

RUN pip install --no-build-isolation git+https://github.com/fanshiqing/grouped_gemm@v1.1.4
