num_nodes: 1
gpus_per_node: 8
model_name: gpt-oss-20b/primus
docker_image: rocm/mlperf:gpt-oss-20b-primus-2026-01-19-20-44-11
sbatch_template: launcher/templates/sbatch.sh.j2
system_config_file: config_MI355X_1x8x1.sh
experiment_type: 'train'
num_experiments: 1
model_store:
  store_name: mlperf_training
  experiment_logdir: '/mlperf/training/gpt_oss_20b_primus/experiments/'
  cache:
    model_dir: /mlperf/training/small_llm_pretraining_nemo/model/
    data_dir: /mlperf/training/small_llm_pretraining_nemo/data/
megatron_config:
  cp: 1
  tp: 1
  pp: 1